steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=wordpress-cloud-run-owner-key > wordpress-cloud-run-owner-key.json' ]
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wordpress-cloud-run/covidscraper', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wordpress-cloud-run/covidscraper']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'covidscraper', '--image', 'gcr.io/wordpress-cloud-run/covidscraper', '--region', 'europe-north1', '--platform', 'managed']
images:
- gcr.io/wordpress-cloud-run/covidscraper